### ISSUE TITLE
Could not find compiler "" error when using with CMake with the Xcode generator on macOS

### ISSUE THREAD

**Issue by phraemer** [TheLartians/Ccache.cmake#6]
Hey!

I've put together a minimal example in a repo to show what's happening:
https://github.com/phraemer/reimagined-octo-guacamole

Probably just me doing something wrong but I couldn't figure it out yet.

See the error here:
https://github.com/phraemer/reimagined-octo-guacamole/runs/2213566880?check_suite_focus=true#step:4:64

Any ideas?
Let me know if I can help in any way

thanks!
James

**Comment by TheLartians** [comment]
Hey, thanks for the issue! The problem seems to be that your project does not specify the C language in the project command, resulting in an error when trying to compile C sources. Imo this is a bug that can easily be fixed from CCache.cmake side, but you can probably resolve this for now by adding `LANGUAGES C CXX` in your CMakeLists `project()` command.

**Comment by TheLartians** [comment]
Should be fixed in v1.2.3!

**Comment by phraemer** [comment]
Ahh perfect! Thanks for looking into it!
